# Generated by Django 4.1.7 on 2023-03-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famille',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='famille',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
