# Generated by Django 4.1.7 on 2023-04-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_historique_delete_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='historique',
        ),
    ]
