# Generated by Django 4.1.7 on 2023-04-17 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_lastrow_delete_historique'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerniereLigne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.famille')),
            ],
        ),
        migrations.DeleteModel(
            name='LastRow',
        ),
    ]
