# Generated by Django 4.2 on 2023-04-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0008_heartrate_alter_derniereligne_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='famille',
            name='email_pour_notification',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
