# Generated by Django 4.2 on 2023-05-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0011_heartrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartrate',
            name='spo2',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
